
#ifndef SOFTWAREENGINEERING_PROJECT2_PLAYER_SWITCH_H
#define SOFTWAREENGINEERING_PROJECT2_PLAYER_SWITCH_H

#endif //SOFTWAREENGINEERING_PROJECT2_PLAYER_SWITCH_H

#include "stack.h"

void winCon(struct player players, square board[BOARD_SIZE][BOARD_SIZE]);